title: Hawa Code
subtitle: "一个懂你的、智能编程助手"
description: "Hawa Code 一个懂你的、智能编程助手"
author: Hawa Code
language: zh-cn
timezone: Asia/Shanghai

url: https://hexo.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

# disqus_shortname: hawacode  # 已禁用Disqus评论功能
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  app_id: 92MM5ICJU3
  api_key: 64d254213e6c3157c3abc2bc74228632
  index_name: hawacode
twitter: hawacode
github: italking/hawa-code
